#!/usr/bin/env python3
"""Replaces the picture ids written as numbers in xindi (``send_cmd_picc(fd, "b", "32")``) by names from xindi/screen/pics.py,
which is generated from display_firmware/project.json (the id of a picture is its position in the list).

    python3 display_firmware/tools/pics_to_names.py [--apply]       (run from src_py/)
"""
import ast
import json
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.abspath(os.path.join(ROOT, "..", ".."))
PICS = [p["key"] for p in json.load(open(os.path.join(SRC, "display_firmware", "project.json")))["pictures"]]
SENDERS = {"send_cmd_picc", "send_cmd_picc2", "send_cmd_pic", "send_cmd_picc1"}


def number(node):
    """The picture id written by a node: "32" / to_string(32) / 32, or None."""
    if isinstance(node, ast.Constant):
        if isinstance(node.value, str) and node.value.isdigit():
            return int(node.value)
    if isinstance(node, ast.Call) and getattr(node.func, "id", "") == "to_string" and len(node.args) == 1:
        a = node.args[0]
        if isinstance(a, ast.Constant) and isinstance(a.value, int):
            return a.value
    return None


def sites(tree):
    """(node, id) of every picture id written as a number."""
    found = []
    for n in ast.walk(tree):
        if isinstance(n, ast.Call):
            f = getattr(n.func, "id", getattr(n.func, "attr", ""))
            if f in SENDERS and len(n.args) >= 3:
                v = number(n.args[2])
                if v is not None:
                    found.append((n.args[2], v))
            elif f == "_picc_group":
                for a in n.args[2:]:
                    v = number(a)
                    if v is not None:
                        found.append((a, v))
        elif isinstance(n, ast.FunctionDef) and n.name == "_zoffset_buttons":
            for d in ast.walk(n):
                if isinstance(d, ast.Dict):
                    for tup in d.values:
                        for a in getattr(tup, "elts", []):
                            v = number(a)
                            if v is not None:
                                found.append((a, v))
    return found


def rewrite(path, apply, ids):
    src = open(path, encoding="utf-8").read()
    tree = ast.parse(src)
    found = sites(tree)
    starts = [0]
    for l in src.split("\n"):
        starts.append(starts[-1] + len(l.encode("utf-8")) + 1)
    data = src.encode("utf-8")
    repl = []
    for node, pid in found:
        a = starts[node.lineno - 1] + node.col_offset
        b = starts[node.end_lineno - 1] + node.end_col_offset
        repl.append((a, b, "pics." + PICS[pid]))
        ids.add(pid)
    for a, b, text in sorted(repl, reverse=True):
        data = data[:a] + text.encode("utf-8") + data[b:]
    print("%s: %d sites" % (os.path.basename(path), len(found)))
    if apply and found:
        out = data.decode("utf-8")
        if "from . import pics" not in out:
            out = out.replace("from . import state as g\n", "from . import state as g\nfrom . import pics\n", 1)
        open(path, "w", encoding="utf-8").write(out)


def main():
    apply = "--apply" in sys.argv
    ids = set()
    for name in ("pages.py", "actions.py", "filelist.py", "wifi_ui.py", "servers.py", "updates.py", "netui.py"):
        rewrite(os.path.join(SRC, "xindi", name), apply, ids)
    module = ['"""Picture ids of the screen firmware (the position in display_firmware/project.json), as strings for',
              'the instructions ``<widget>.picc=<id>``. Generated by display_firmware/tools/pics_to_names.py."""', ""]
    module += ['%s = "%d"' % (PICS[i], i) for i in sorted(ids)]
    print("%d distinct pictures" % len(ids))
    if apply:
        open(os.path.join(SRC, "xindi", "pics.py"), "w", encoding="utf-8").write("\n".join(module) + "\n")


if __name__ == "__main__":
    main()
